// web/src/routes/auth/register.svelte
<script>
	import LoginForm from "$lib/components/auth/LoginForm.svelte";
</script>

<svelte:head>
	<title>Register - Anchor</title>
</svelte:head>
<main class="flex h-full w-screen items-center justify-center">
	<div class="flex h-full w-full items-center justify-center">
		<LoginForm name="Register" />
	</div>
</main>

// client/pages/auth/register.tsx
import type { NextPage } from "next";
import Head from "next/head";
import AuthForm from "../../components/auth/AuthForm";

const Register: NextPage = () => (
	<>
		<Head>
			<title>Register - Anchor</title>
		</Head>
		<main className="flex h-full w-screen items-center justify-center">
			<div className="flex h-full w-full items-center justify-center">
				<AuthForm name="Register" />
			</div>
		</main>
	</>
);

export default Register;
