// web/src/lib/components/shared/Footer.svelte
<footer class="grid w-full grid-cols-4 bg-gray-900 p-10 text-white">
	<div class="flex flex-col items-center space-y-2">
		<a href="/" class="font-medium">Home</a>
		<a href="/" class="font-medium">Register</a>
		<a href="/" class="font-medium">Login</a>
		<a href="/" class="font-medium">Home</a>
	</div>
</footer>

// client/components/shared/Footer.tsx
export default function Footer() {
	return (
		<footer className="grid w-full grid-cols-4 bg-gray-900 p-10 text-white">
			<div className="flex flex-col items-center space-y-2">
				<a href="/" className="font-medium">
					Home
				</a>
				<a href="/" className="font-medium">
					Register
				</a>
				<a href="/" className="font-medium">
					Login
				</a>
				<a href="/" className="font-medium">
					Home
				</a>
			</div>
		</footer>
	);
}
