// web/src/lib/components/Navbar.svelte
<script>
	import { user } from "../stores/userStore";
</script>

<nav class="bg-cyan-700 w-screen py-4">
	<div class="container mx-auto flex items-center justify-between">
		<div>
			<a class="text-2xl text-white font-semibold" href="/">Anchor</a>
		</div>
		{#if $user}
			<div class="flex items-center space-x-4 justify-center text-white font-medium">
				<a href="/focus">Focus Mode</a>
				<a href="/insights">Insights</a>
			</div>
		{/if}
		<div>
			{#if $user}
				<img src={""} alt="" />
			{:else}
				<a href="/auth/login" class="px-4 py-2 shadow-md bg-white rounded-md text-black font-medium hover:bg-gray-300"
					>Login</a
				>
			{/if}
		</div>
	</div>
</nav>

// client/components/shared/Navbar.tsx
import useUserStore from "../../stores/userStore";

const Navbar = () => {
	const user = useUserStore((s) => s.user);

	return (
		<nav className="bg-blue-700 py-4">
			<div className="container mx-auto flex items-center justify-between px-8">
				<div>
					<a className="text-2xl font-semibold text-white" href="/">
						Anchor
					</a>
				</div>
				{user && (
					<div className="flex items-center justify-center space-x-4 font-medium text-white">
						<a href="/focus">Focus Mode</a>
						<a href="/insights">Insights</a>
					</div>
				)}
				<div className="space-x-4">
					{user && (
						<>
							<img src="" alt="" />
							<a
								href="/auth/register"
								className="rounded-md bg-white px-4 py-2 font-medium text-black shadow-md hover:bg-gray-300"
							>
								Get Started
							</a>
							<a href="/auth/login" className="hidden font-medium text-white hover:text-gray-300 md:inline">
								Or Login
							</a>
						</>
					)}
				</div>
			</div>
		</nav>
	);
};
export default Navbar;
